Team7MVC/Models/Customers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Team7MVC.Models
{
    public class Customers
    {
        [Display(Name = "會員ID")]
        public int CustomerID { get; set; }
        [Display(Name = "帳號")]
        public string Account { get; set; }
        [Required ]
        [DataType(DataType.Password)]
        [Display(Name = "密碼")]
        public string Password { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "新密碼")]
        public string NewPassword { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [System.ComponentModel.DataAnnotations.Compare("NewPassword", ErrorMessage = "密碼和確認密碼不相符")]
        [Display(Name = "確認新密碼")]
        public string ConfirmPassword { get; set; }
        [Display(Name = "名字")]
        public string CustomerName { get; set; }
        [Display(Name = "性別")]
        public string Gender { get; set; }
        [Display(Name = "生日")]
        public DateTime Birthday { get; set; }
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Display(Name = "地址")]
        public string Address { get; set; }
        [Display(Name = "手機")]
        public string Phone { get; set; }
        [Display(Name = "VIP")]
        public bool VIP { get; set; }
        [Display(Name = "圖片")]
        public string Picture { get; set; }
        [Display(Name = "城市")]
        public string City { get; set; }
    }
}

Team7MVC/Models/OrderDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Team7MVC.Models
{
    public class OrderDetails
    {
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public float Discount { get; set; }
    }
}

Team7MVC/ViewModels/OrderDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Team7MVC.ViewModels
{
    public class OrderDetailViewModel
    {
        public CustomerDetail customerDetails { get; set; }

        public List<ProductDetail> productDetails { get; set; }
    }
    public class CustomerDetail
    {
        public string BillName { get; set; }
        public string Email { get; set; }
        public string BillCity { get; set; }
        public string BillAddress { get; set; }
        public string BillPhone { get; set; }
        public string ShipName { get; set; }
        public string ShipCity { get; set; }
        public string ShipAddress { get; set; }
        public string ShipPhone { get; set; }
        public string PayWay { get; set; }
        public int Freight { get; set; }
    }

    public class ProductDetail
    {
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public int UnitPrice { get; set; }
        public string Picture { get; set; }
    }
}

Team7MVC/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Team7MVC.Models;
using Team7MVC.Repositories;

namespace Team7MVC.Controllers
{
    public class CustomerController : Controller
    {
        public readonly CustomerRepository _repo;
       

        public CustomerController()
        {
            _repo = new CustomerRepository();
        }

        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CustomerEdit()
        {
            var customers = _repo.GetCustomersId(User.Identity.Name);
            return View(customers);
        }

        [HttpPost]
        public ActionResult CustomerEdit(string CustomerName, string Account, string Gender, string Email, string Phone, string Address, DateTime Birthday, string VIP)
        {
            Customers customers = new Customers()
            {
                CustomerName = CustomerName,
                Account = User.Identity.Name,
                Gender = Gender,
                Birthday = Birthday,
                Email = Email,
                Phone = Phone,
                Address = Address
            };

            _repo.UpdateCustomer(customers);

            return RedirectToAction("CustomerEdit");
        }

        [HttpGet]
        public ActionResult ChangePassword()
        {
            var customers = _repo.GetCustomersId(User.Identity.Name);
            return View(customers);
        }

        [HttpPost]
        public ActionResult ChangePassword(Customers customers)
        {

            if (!ModelState.IsValid)
            {
                if(customers.NewPassword != customers.ConfirmPassword)
                {
                    return View(customers);

                }
                return View(customers);
            }

            //if (customers.NewPassword != customers.ConfirmPassword)
            //{
            //    return View(customers);
            //}


            if (customers.NewPassword == customers.ConfirmPassword)
            {
                _repo.UpdatePassword(customers);
            }

            return RedirectToAction("ChangePassword");

        }

        [HttpGet]
        public ActionResult PurchaseList()
        {
            var orders = _repo.OrderQuery(User.Identity.Name);
            return View(orders);
        }
        [HttpGet]
        public ActionResult Order_Details(int Id)
        {
            var orders_Details = _repo.QueryOrderDetails(Id);
            return View(orders_Details);
        }

        [HttpGet]
        public ActionResult PaywayInfo()
        {
            var PaywayInfo = _repo.QueryPaywayInfo(User.Identity.Name);
            return View(PaywayInfo);
        }
    }
}

Team7MVC/Controllers/OrderDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Team7MVC.Repositories;
using Team7MVC.ViewModels;

namespace Team7MVC.Controllers
{
    public class OrderDetailController : Controller
    {
        public readonly OrderDetailRepository _repo;

        public OrderDetailController()
        {
            _repo = new OrderDetailRepository();
        }

        // GET: OrderDetail
        public ActionResult Index()
        {
            return View();
        }

        // GET: OrderDetail
        [HttpGet]
        public ActionResult OrderDetail()
        {
            OrderDetailViewModel orderdetailList;
            orderdetailList = _repo.OrderDetailList(User.Identity.Name);

            return View(orderdetailList);
        }
    }
}

Team7MVC/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Team7MVC.Models;
using Team7MVC.Repositories;
using Team7MVC.ViewModels;

namespace Team7MVC.Controllers
{
    public class ProductController : Controller
    {
        public readonly ProductRepository _repo;

        public ProductController()
        {
            _repo = new ProductRepository();
        }
        // GET: Product
        [HttpGet]
        public ActionResult Index()
        {
            List<Products> products;

            products = _repo.GetProducts();

            return View(products);
        }



        #region 產品搜尋

        [HttpPost]
        public ActionResult SearchProductName(string search)
        {
            List<Products> products;

            if (search != null)
            {
                products = _repo.GetProducts(search);
            }
            else
            {
                products = _repo.GetProducts();
            }

            ViewData.Model = products;
            return View("Index");
        }

        [HttpPost]
        public ActionResult SearchProductYear(int? Year_s, int? Year_e)
        {
            List<Products> products;

            if (Year_e == null && Year_s != null)
            {
                products = _repo.GetProducts(Year_s);
            }
            else if (Year_s != null)
            {
                products = _repo.GetProducts(Year_s, Year_e);
            }
            else
            {
                products = _repo.GetProducts();
            }

            ViewData.Model = products;
            return View("Index");
        }

        [HttpPost]
        public ActionResult SearchProductPrice(decimal? Price_s, decimal? Price_e)
        {
            List<Products> products;

            if (Price_e == null && Price_s != null)
            {
                products = _repo.GetProducts(Price_s);
            }
            else if (Price_s != null)
            {
                products = _repo.GetProducts(Price_s, Price_e);
            }
            else
            {
                products = _repo.GetProducts();
            }

            ViewData.Model = products;
            return View("Index");
        }

        #endregion

        #region 產品分類

        [HttpPost]
        public ActionResult ProductOrigin(string[] Origin)
        {
            List<Products> products;

            if (Origin != null)
            {
                products = _repo.GetProducts(Origin, 1);
            }
            else
            {
                products = _repo.GetProducts();
            }

            ViewData.Model = products;
            return View("Index");
        }

        [HttpPost]
        public ActionResult ProductCategory(string[] Category)
        {
            List<Products> products;

            if (Category != null)
            {
                products = _repo.GetProducts(Category, 2);
            }
            else
            {
                products = _repo.GetProducts();
            }

            ViewData.Model = products;
            return View("Index");
        }

        public ActionResult NewProduct()
        {
            List<Products> products;


            products = _repo.GetNewProducts();

            ViewData.Model = products;
            return View("Index");
        }

        public ActionResult HotProduct()
        {
            List<Products> products;


            products = _repo.GetHotProducts();

            ViewData.Model = products;
            return View("Index");
        }

        public ActionResult ExpensiveProduct()
        {
            List<Products> products;


            products = _repo.GetExpensiveProducts();

            ViewData.Model = products;
            return View("Index");
        }

        #endregion

        [HttpGet]
        public ActionResult ProductDetail(int Id)
        {
            var product = _repo.GetProductById(Id);
            return View(product);
        }

        [Authorize]
        [HttpPost]
        public ActionResult ProductDetail(int ProductId, int buyQty)
        {
            //var product = _repo.GetProductById(Id);

            //ShopListsViewModel shopLists = new ShopListsViewModel
            //{
            //    ProductId = product.ProductID,
            //    Price = product.UnitPrice,
            //    Quantity = buyQty
            //};

            _repo.CreateShoppingCartData(User.Identity.Name, ProductId, buyQty);

            return RedirectToAction("ShoppingCart");
        }

        [Authorize]
        public ActionResult ShoppingCart()
        {
            List<ShopListsViewModel> shopLists;
            shopLists = _repo.ShopList(User.Identity.Name);

            return View(shopLists);
        }

        [HttpPost]
        public ActionResult ShoppingCart(string nothing)
        {
            return RedirectToAction("Payment");
        }

        [HttpGet]
        public ActionResult DeleteShoppingCartProduct(int ProductID)
        {
            var CustomerID = _repo.GetCustomerID(User.Identity.Name);
            _repo.DeleteShopListProduct(CustomerID, ProductID);

            return RedirectToAction("ShoppingCart");
        }

        [Authorize]
        [HttpGet]
        public ActionResult Payment()
        {
            PaymentViewModel paymentViewModel = new PaymentViewModel();
            List<ShopListsViewModel> shopList;
            shopList = _repo.ShopList(User.Identity.Name);
            paymentViewModel.shopList = shopList;

            return View(paymentViewModel);
        }

        [HttpPost]
        public ActionResult Payment(/*DateTime RequiredDate,*/ string BillFirstName, string BillLastName, string BillPhone, string BillCity, string BillAddress, string ShipFirstName, string ShipLastName, string ShipPhone, string ShipCity, string ShipAddress, string PayWay, string CreditCardNo4, string CreditCardNo8, string CreditCardNo12, string CreditCardNo16, string CreditCardMM, string CreditCardYY, int? CreditCardCSC, string IdentityCard)
        {
            CustomerPayment customerPayment;

            if (string.IsNullOrEmpty(CreditCardNo4) && string.IsNullOrEmpty(CreditCardNo8) && string.IsNullOrEmpty(CreditCardNo12) && string.IsNullOrEmpty(CreditCardNo16) && string.IsNullOrEmpty(CreditCardMM) && string.IsNullOrEmpty(CreditCardYY) && CreditCardCSC == null && string.IsNullOrEmpty(IdentityCard))
            {
                if (string.IsNullOrEmpty(BillFirstName) && string.IsNullOrEmpty(BillLastName) && string.IsNullOrEmpty(BillCity) && string.IsNullOrEmpty(BillAddress) && string.IsNullOrEmpty(BillPhone))
                {
                    customerPayment = new CustomerPayment()
                    {
                        OrderDate = DateTime.Now,
                        //RequiredDate = DateTime.Now,
                        BillName = ShipFirstName + ShipLastName,
                        BillPhone = ShipPhone,
                        BillCity = ShipCity,
                        BillAddress = ShipAddress,
                        ShipperID = 1,
                        ShipName = ShipFirstName + ShipLastName,
                        ShipPhone = ShipPhone,
                        ShipAddress = ShipAddress,
                        ShipCity = ShipCity,
                        PayWay = "ATM",
                        PayDate = DateTime.Now,
                        Freight= 100
                    };
                }
                else
                {
                    customerPayment = new CustomerPayment()
                    {
                        OrderDate = DateTime.Now,
                        //RequiredDate = DateTime.Now,
                        BillName = BillFirstName + BillLastName,
                        BillPhone = BillPhone,
                        BillCity = BillCity,
                        BillAddress = BillAddress,
                        ShipperID = 1,
                        ShipName = ShipFirstName + ShipLastName,
                        ShipPhone = ShipPhone,
                        ShipAddress = ShipAddress,
                        ShipCity = ShipCity,
                        PayWay = "ATM",
                        PayDate = DateTime.Now,
                        Freight = 100
                    };
                }

            }
            else
            {
                if (string.IsNullOrEmpty(BillFirstName) && string.IsNullOrEmpty(BillLastName) && string.IsNullOrEmpty(BillCity) && string.IsNullOrEmpty(BillAddress) && string.IsNullOrEmpty(BillPhone))
                {
                    customerPayment = new CustomerPayment()
                    {
                        OrderDate = DateTime.Now,
                        //RequiredDate = DateTime.Now,
                        BillName = ShipFirstName + ShipLastName,
                        BillPhone = ShipPhone,
                        BillCity = ShipCity,
                        BillAddress = ShipAddress,
                        ShipperID = 1,
                        ShipName = ShipFirstName + ShipLastName,
                        ShipPhone = ShipPhone,
                        ShipAddress = ShipAddress,
                        ShipCity = ShipCity,
                        PayWay = "CreditCard",
                        CreditCardNo = CreditCardNo4 + CreditCardNo8 + CreditCardNo12 + CreditCardNo16,
                        CreditCardCSC = CreditCardCSC,
                        CreditCardDate = CreditCardMM + CreditCardYY,
                        IdentityCard = IdentityCard,
                        PayDate = DateTime.Now,
                        Freight = 100
                    };
                }
                else
                {
                    customerPayment = new CustomerPayment()
                    {
                        OrderDate = DateTime.Now,
                        //RequiredDate = DateTime.Now,
                        BillName = BillFirstName + BillLastName,

Team7MVC/Views/Customer/ChangePassword.cshtml
@model Team7MVC.Models.Customers

@{
    ViewBag.Title = "ChangePassword";
}

<div class="content">
    <div class="row">
        <div class="col-md-8" style="margin:auto auto;">
            <div class="card card-user">
                <div class="card-header">
                    <h5 class="card-title">個人資料修改</h5>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("ChangePassword", "Customer", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-group">
                            輸入舊密碼:
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            輸入新密碼:
                            @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control", @Id = "NewPassword" } })
                            @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            再次輸入密碼:
                            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control", @Id = "ConfirmPassword" } })
                            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                        </div>
                        <span class="tip" style="color: red;">兩次輸入的密碼不一致</span>

                        <div class="row">
                            <div class="update ml-auto mr-auto mb-3">
                                <button type="submit" class="btn btn-primary btn-round">更新資料</button>
                            </div>
                        </div>
                    }
                </div>

            </div>
        </div>

    </div>

</div>

@section JQuery
{
    <script>
        $(function () {
            $("header nav")
                .removeClass("navbar-dark")
                .addClass("navbar-light");
            $("header a img").prop("src", "/Assets/img_Index/logo_dark.png");
            $("header .nav-item > a")
                .removeClass("text-white")
                .addClass("text-dark");
            $("#search-input")
                .removeClass("whiteplaceholder")
                .removeClass("text-white")
                .addClass("blackplaceholder")
                .addClass("text-dark");
            $("header").addClass("fixed-header");
        });
        $(".tip").hide();

        $("#logo").css("color", "#000");
       

        $(document).ready(function () {

            $("li").each(function () {

                if ($(this).hasClass("user-active")) {
                    $(this).removeClass("user-active");
                }

            });

            $("#sidebar_Change_Password").addClass("user-active");

            $("li").on("click", function () {
                $("#sidebar_Change_Password").removeClass("user-active");
                $(this).addClass("user-active");
            });
        });
    </script>
}

Team7MVC/Views/Customer/Order_Details.cshtml
@model IEnumerable<Team7MVC.ViewModels.ShopListsViewModel>

@{
    ViewBag.Title = "Order_Details";
    int count = 1;
}

<link href="~/Assets/css/User/Order_Details.css" rel="stylesheet" />

<div class="Detail">

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-10 card" style="margin:auto auto">
                    @*<div class="card-header">
                        </div>*@
                    <div class="card-body">
                        <div>
                            <table class="table table-hover">
                                <thead class="">
                                    <tr>
                                        <th class="Detail-table-title">序</th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.ProductName)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Year)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Origin)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Price)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Quantity)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.TotalCost)
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        @*@Html.Partial("ShoppingCartPartial")*@
                                        <tr>
                                            <!-- <td colspan="8" class="Detail-table-row">您的清單內目前沒有任何商品</td> -->
                                            <td class="Detail-table-title">@count</td>
                                            @{ count++;}

                                            <td class="product-name">
                                                <div>
                                                    <a href="@Url.Action("ProductDetail","Product" , new { id = item.ProductId })">
                                                        <img src="~/Assets/images/img_Products/@Html.DisplayFor(modelItem => item.Picture)" alt="商品" />
                                                        @Html.DisplayFor(modelItem => item.ProductName)
                                                    </a>
                                                </div>
                                                
                                            </td>
                                            <td class="Detail-table-title">@Html.DisplayFor(modelItem => item.Year)</td>
                                            <td class="Detail-table-title">@Html.DisplayFor(modelItem => item.Origin)</td>
                                            <td class="Detail-table-title">@Html.DisplayFor(modelItem => item.Price)</td>
                                            <td class="Detail-table-title">@Html.DisplayFor(modelItem => item.Quantity)</td>
                                            <td class="Detail-table-title">@Html.DisplayFor(modelItem => item.TotalCost)</td>
                                            
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


@section JQuery
{
    <script>
        $(function () {
            $("header nav")
                .removeClass("navbar-dark")
                .addClass("navbar-light");
            //$("header a img").prop("src", "/Assets/images/img_Index/logo_dark.png");
            $("header .nav-item > a")
                .removeClass("text-white")
                .addClass("text-dark");
            $("#search-input")
                .removeClass("whiteplaceholder")
                .removeClass("text-white")
                .addClass("blackplaceholder")
                .addClass("text-dark");
            $("header").addClass("fixed-header");

            $("#logo").css("color", "#000");

            $(document).ready(function () {

                $("li").each(function () {

                    if ($(this).hasClass("user-active")) {
                        $(this).removeClass("user-active");
                    }

                });

                $("#sidebar_Purchase_List").addClass("user-active");

                $("li").on("click", function () {
                    $("#sidebar_Purchase_List").removeClass("user-active");
                    $(this).addClass("user-active");
                });
            });

        });
    </script>
}

Team7MVC/Views/Customer/PaywayInfo.cshtml
@{
    ViewBag.Title = "PaywayInfo";
}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-10 card" style="margin:auto auto">
                <div class="card-header">
                   <h3> My Credit Card </h3>
                    @Html.ActionLink("新增信用卡", "Create", "", new { @class = "btn btn-secondary" })
                </div>
                <div class="card-body">
                    <div>
                        <table class="table table-hover">
                            <thead class="">
                                <tr>

                                    <th></th>
                                    <a href="~/Views/Customer/PaywayInfo.cshtml">~/Views/Customer/PaywayInfo.cshtml</a>
                                </tr>
                            </thead>
                            <tbody>
                                @*@foreach (var item in Model)
        {*@
                                <tr>
                                    <td class="text-center"><h4>目前尚無信用卡資訊</h4></td>
                                </tr>
                               
                                @*}*@
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section JQuery
{
    <script>
        $(function () {
            $("header nav")
                .removeClass("navbar-dark")
                .addClass("navbar-light");
            //$("header a img").prop("src", "/Assets/images/img_Index/logo_dark.png");
            $("header .nav-item > a")
                .removeClass("text-white")
                .addClass("text-dark");
            $("#search-input")
                .removeClass("whiteplaceholder")
                .removeClass("text-white")
                .addClass("blackplaceholder")
                .addClass("text-dark");
            $("header").addClass("fixed-header");

            $("#logo").css("color", "#000");
            //$(".account").hide();
            //$("#my-account").mouseenter(
            //    function () {
            //        //toggle 像電燈般開闔物件
            //        $(this).find(".account").toggle();
            //    }
            //);
            $(document).ready(function () {

                $("li").each(function () {

                    if ($(this).hasClass("user-active")) {
                        $(this).removeClass("user-active");
                    }

                });

                $("#sidebar_Payway_Info").addClass("user-active");

                $("li").on("click", function () {
                    $("#sidebar_Payway_Info").removeClass("user-active");
                    $(this).addClass("user-active");
                });
            });

        });
    </script>
}